In [ ]:
import pandas as pd
from apt_project import *

ImportError: attempted relative import with no known parent package

In [5]:
master_df

,id,type,name,description,created,modified,raw
0,x-mitre-collection--1f5f1533-f617-4ca8-9ab4-6a...,x-mitre-collection,Enterprise ATT&CK,ATT&CK for Enterprise provides a knowledge bas...,2018-01-17T12:56:55.080Z,2025-11-13T14:00:00.188Z,"{'type': 'x-mitre-collection', 'id': 'x-mitre-..."
1,x-mitre-matrix--eafc1b4c-5e56-4965-bd4e-66a6a8...,x-mitre-matrix,Enterprise ATT&CK,Below are the tactics and technique representi...,2018-10-17T00:14:20.652Z,2025-04-25T14:41:40.982Z,"{'type': 'x-mitre-matrix', 'spec_version': '2...."
2,course-of-action--00d7d21b-69d6-4797-88a2-c86f...,course-of-action,Password Filter DLL Mitigation,Ensure only valid password filters are registe...,2018-10-17T00:14:20.652Z,2025-04-18T17:59:39.912Z,"{'type': 'course-of-action', 'spec_version': '..."
3,course-of-action--02f0f92a-0a51-4c94-9bda-6437...,course-of-action,Space after Filename Mitigation,Prevent files from having a trailing space aft...,2018-10-17T00:14:20.652Z,2025-04-18T17:59:40.127Z,"{'type': 'course-of-action', 'spec_version': '..."
4,course-of-action--03c0c586-50ed-45a7-95f4-f496...,course-of-action,HISTCONTROL Mitigation,Prevent users from changing the <code>HISTCONT...,2018-10-17T00:14:20.652Z,2025-04-18T17:59:40.291Z,"{'type': 'course-of-action', 'spec_version': '..."
...,...,...,...,...,...,...,...
24767,relationship--fff9a9cb-3032-4f18-a626-ce34a82e...,relationship,None,[ToddyCat](https://attack.mitre.org/groups/G10...,2024-01-23T20:36:19.677Z,2025-04-16T23:00:48.213Z,"{'type': 'relationship', 'spec_version': '2.1'..."
24768,relationship--ffff35dc-3741-4fba-9680-f0fbe321...,relationship,None,[Bisonal](https://attack.mitre.org/software/S...,2022-01-27T18:04:46.484Z,2025-04-16T23:00:48.437Z,"{'type': 'relationship', 'spec_version': '2.1'..."
24769,relationship--ffffed15-5695-44b9-b85b-89ba8187...,relationship,None,[ZxShell](https://attack.mitre.org/software/S0...,2019-09-24T14:19:05.322Z,2025-04-28T16:19:23.875Z,"{'type': 'relationship', 'spec_version': '2.1'..."
24770,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,identity,The MITRE Corporation,,2017-06-01T00:00:00.000Z,2025-03-19T15:00:40.855Z,"{'modified': '2025-03-19T15:00:40.855Z', 'name..."
24771,marking-definition--fa42a846-8d90-4e51-bc29-71...,marking-definition,None,None,2017-06-01T00:00:00.000Z,None,{'definition': {'statement': 'Copyright 2015-2...

In [4]:
tech_df.head()

,id,tech_name,external_id,description,platforms,kill_chain_phases,raw
0,attack-pattern--0042a9f5-f053-4769-b3ef-9ad018...,Extra Window Memory Injection,T1055.011,Adversaries may inject malicious code into pro...,[Windows],"[defense-evasion, privilege-escalation]","{'type': 'attack-pattern', 'spec_version': '2...."
1,attack-pattern--005a06c6-14bf-4118-afa0-ebcd8a...,Scheduled Task,T1053.005,Adversaries may abuse the Windows Task Schedul...,[Windows],"[execution, persistence, privilege-escalation]","{'type': 'attack-pattern', 'spec_version': '2...."
2,attack-pattern--005cc321-08ce-4d17-b1ea-cb5275...,Socket Filters,T1205.002,Adversaries may attach filters to a network so...,"[Linux, macOS, Windows]","[defense-evasion, persistence, command-and-con...","{'type': 'attack-pattern', 'spec_version': '2...."
3,attack-pattern--00d0b012-8a03-410e-95de-5826bf...,Indicator Removal from Tools,T1066,If a malicious tool is detected and quarantine...,"[Linux, macOS, Windows]",[defense-evasion],"{'type': 'attack-pattern', 'spec_version': '2...."
4,attack-pattern--00f90846-cbd1-4fc5-9233-df5c2b...,Archive via Utility,T1560.001,Adversaries may use utilities to compress and/...,"[Linux, macOS, Windows]",[collection],"{'type': 'attack-pattern', 'spec_version': '2...."