In [2]:
import sys
from pathlib import Path

ROOT = Path().resolve().parents[1] # go up n levels (adjust as needed)
sys.path.append(str(ROOT))

from config import PROJECT_ROOT, APT_ROOT
from apt_project import *

In [ ]:
import pandas as pd

In [13]:
master_df

,id,type,name,description,created,modified,raw
0,x-mitre-collection--1f5f1533-f617-4ca8-9ab4-6a...,x-mitre-collection,Enterprise ATT&CK,ATT&CK for Enterprise provides a knowledge bas...,2018-01-17T12:56:55.080Z,2025-11-13T14:00:00.188Z,"{'type': 'x-mitre-collection', 'id': 'x-mitre-..."
1,x-mitre-matrix--eafc1b4c-5e56-4965-bd4e-66a6a8...,x-mitre-matrix,Enterprise ATT&CK,Below are the tactics and technique representi...,2018-10-17T00:14:20.652Z,2025-04-25T14:41:40.982Z,"{'type': 'x-mitre-matrix', 'spec_version': '2...."
2,course-of-action--00d7d21b-69d6-4797-88a2-c86f...,course-of-action,Password Filter DLL Mitigation,Ensure only valid password filters are registe...,2018-10-17T00:14:20.652Z,2025-04-18T17:59:39.912Z,"{'type': 'course-of-action', 'spec_version': '..."
3,course-of-action--02f0f92a-0a51-4c94-9bda-6437...,course-of-action,Space after Filename Mitigation,Prevent files from having a trailing space aft...,2018-10-17T00:14:20.652Z,2025-04-18T17:59:40.127Z,"{'type': 'course-of-action', 'spec_version': '..."
4,course-of-action--03c0c586-50ed-45a7-95f4-f496...,course-of-action,HISTCONTROL Mitigation,Prevent users from changing the <code>HISTCONT...,2018-10-17T00:14:20.652Z,2025-04-18T17:59:40.291Z,"{'type': 'course-of-action', 'spec_version': '..."
...,...,...,...,...,...,...,...
24767,relationship--fff9a9cb-3032-4f18-a626-ce34a82e...,relationship,None,[ToddyCat](https://attack.mitre.org/groups/G10...,2024-01-23T20:36:19.677Z,2025-04-16T23:00:48.213Z,"{'type': 'relationship', 'spec_version': '2.1'..."
24768,relationship--ffff35dc-3741-4fba-9680-f0fbe321...,relationship,None,[Bisonal](https://attack.mitre.org/software/S...,2022-01-27T18:04:46.484Z,2025-04-16T23:00:48.437Z,"{'type': 'relationship', 'spec_version': '2.1'..."
24769,relationship--ffffed15-5695-44b9-b85b-89ba8187...,relationship,None,[ZxShell](https://attack.mitre.org/software/S0...,2019-09-24T14:19:05.322Z,2025-04-28T16:19:23.875Z,"{'type': 'relationship', 'spec_version': '2.1'..."
24770,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,identity,The MITRE Corporation,,2017-06-01T00:00:00.000Z,2025-03-19T15:00:40.855Z,"{'modified': '2025-03-19T15:00:40.855Z', 'name..."
24771,marking-definition--fa42a846-8d90-4e51-bc29-71...,marking-definition,None,None,2017-06-01T00:00:00.000Z,None,{'definition': {'statement': 'Copyright 2015-2...

In [12]:
tech_df.head()

,id,tech_name,external_id,description,platforms,kill_chain_phases,raw
0,attack-pattern--0042a9f5-f053-4769-b3ef-9ad018...,Extra Window Memory Injection,T1055.011,Adversaries may inject malicious code into pro...,[Windows],"[defense-evasion, privilege-escalation]","{'type': 'attack-pattern', 'spec_version': '2...."
1,attack-pattern--005a06c6-14bf-4118-afa0-ebcd8a...,Scheduled Task,T1053.005,Adversaries may abuse the Windows Task Schedul...,[Windows],"[execution, persistence, privilege-escalation]","{'type': 'attack-pattern', 'spec_version': '2...."
2,attack-pattern--005cc321-08ce-4d17-b1ea-cb5275...,Socket Filters,T1205.002,Adversaries may attach filters to a network so...,"[Linux, macOS, Windows]","[defense-evasion, persistence, command-and-con...","{'type': 'attack-pattern', 'spec_version': '2...."
3,attack-pattern--00d0b012-8a03-410e-95de-5826bf...,Indicator Removal from Tools,T1066,If a malicious tool is detected and quarantine...,"[Linux, macOS, Windows]",[defense-evasion],"{'type': 'attack-pattern', 'spec_version': '2...."
4,attack-pattern--00f90846-cbd1-4fc5-9233-df5c2b...,Archive via Utility,T1560.001,Adversaries may use utilities to compress and/...,"[Linux, macOS, Windows]",[collection],"{'type': 'attack-pattern', 'spec_version': '2...."

In [3]:
umd_apts_df

,slug,original_method,event_date,reported_date,year,month,actor,actor_type,organization,industry_code,...,org_data,cust_data,description,source_url,country,actor_country,state,county,change_log,apt_group
0,51de7a6f8a84858e,1,2014-06-30,NaN,2014,6,Green Dragon Crew,Hacktivist,Privatbank,52,...,NaN,NaN,Hackers from the Green Dragon Crew hack Privat...,http://en.itar-tass.com/economy/738359,Ukraine,Ukraine,NaN,NaN,NaN,dragonok
1,2c0603efa7d7541b,1,2015-02-28,NaN,2015,2,f AKA @Cleaver,Undetermined,frontalot.com,81,...,NaN,NaN,f AKA @CIeaver hacks frontalot.com and dumps a...,https://web.archive.org/web/20150315024644/htt...,United States of America,Undetermined,Undetermined,Undetermined,NaN,cleaver
2,1147a5bf27ee80f6,1,2015-03-01,NaN,2015,3,Ministry of State Security's (MSS) Guangdong S...,Nation-State,Hanford Site,92,...,NaN,NaN,Hackers conducted a combination of financially...,https://www.politico.com/news/2020/07/21/doj-c...,United States of America,China,Washington,Benton,NaN,apt3
3,649f14c0fd38146e,1,2015-05-31,NaN,2015,5,APT32,Nation-State,Armed Forces of the Philippines,92,...,NaN,NaN,Vietnamese threat actor Ocean Lotus has compro...,https://www.volexity.com/blog/2017/11/06/ocean...,Philippines,Viet Nam,NaN,NaN,NaN,apt32
4,c786e72aab5694ab,1,2015-05-31,NaN,2015,5,APT32,Nation-State,ASEAN Investment,92,...,NaN,NaN,Vietnamese threat actor Ocean Lotus has compro...,https://www.volexity.com/blog/2017/11/06/ocean...,Undetermined,Viet Nam,NaN,NaN,NaN,apt32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,z1r8m5x2c9v4k7t3,1,2025-03-25,2025-10-23,2025,3,NGB 3rd Technical Surveillance Bureau (Lazarus...,Nation-state,Undisclosed European drone manufacturer,31,...,None reported,None reported,North Korean operators approached European def...,https://thehackernews.com/2025/10/north-korean...,Undetermined,Korea (the Democratic People's Republic of),Undetermined,Undetermined,NaN,lazarus group
421,q6v2r9x1c7m5t3k8,1,2025-09-01,2025-10-24,2025,9,APT36 (Transparent Tribe),Nation-state,Undisclosed Indian government or infrastructur...,92,...,Directory listings,None reported,Pakistan-linked APT36 used themed lures and HT...,https://thehackernews.com/2025/10/apt36-target...,India,Pakistan,NaN,NaN,NaN,transparent tribe
422,z7m3t1p9v4x2k8r5,1,2025-07-15,2025-10-21,2025,7,Ministry of State Security's (MSS) (Salt Typhoon),Nation-state,Undisclosed European telecommunications company,51,...,None reported,AD/infra configuration and credentials,China-nexus operators breached a telecom by ex...,https://hackread.com/salt-typhoon-apt-telecom-...,Undetermined,China,Undetermined,Undetermined,NaN,salt typhoon
423,b9e1f4d2c7a3e805,1,2025-09-01,2025-10-30,2025,9,UNC6384,Nation-State,Undisclosed Belgian Diplomatic Entities,92,...,Undisclosed volume of diplomatic correspondenc...,Undisclosed volume of diplomatic correspondenc...,China-linked UNC6384 conducted a cyber-espiona...,https://therecord.media/belgium-hungary-diplom...,Belgium,China,NaN,NaN,NaN,mustang panda
424,f1d3b7e9c2a4f608,1,2025-09-01,2025-10-30,2025,9,UNC6384,Nation-State,Undisclosed Hungarian Diplomatic Entities,92,...,Undisclosed volume of diplomatic correspondenc...,Undisclosed volume of diplomatic correspondenc...,China-linked UNC6384 conducted a cyber-espiona...,https://therecord.media/belgium-hungary-diplom...,Hungary,China,NaN,NaN,NaN,mustang panda